name: Update_manifest

on:
  workflow_run:
    workflows: [common_workflow]
    branches:
      - staging-test
    types:
      - completed

#--------------------------------------------------------- UPDATE MANIFEST FILES WITH COMMIT HASHES -----------------------------------------------------------------
jobs:
  Change_dev_manifest_with_commit_hash:
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/dev-test02' }}
    steps:
      - uses: actions/checkout@v2
      - run: echo change commit hash in manifest
      - run: echo change commit hash in manifest
      - run: echo change commit hash in manifest
