name: Update_manifest

on:
  workflow_run:
    workflows: [Update_manifest]
    branches:
      - staging-test
      - prod-test
    types:
      - completed

#--------------------------------------------------------- UPDATE MANIFEST FILES WITH COMMIT HASHES -----------------------------------------------------------------
jobs:
  Change_dev_manifest_with_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo change commit hash in manifest
