name: Update_manifest3

on:
  workflow_run:
    workflows: [Update_manifest2]
    branches:
      - dev-test02
      - staging-test
      - prod-test

    types:
      - completed

#--------------------------------------------------------- UPDATE MANIFEST FILES WITH COMMIT HASHES -----------------------------------------------------------------
jobs:
  Change_dev_manifest_with_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo change commit hash in manifest
