name: workflow_2
on:
  push:
    branches:
      - test
    workflow_run:
      workflows: ['workflow_4']
      types:
        - completed
jobs:
  Second_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo workflow 2
