name: Update_prod_manifest
on:
  push:
    branches:
      - test
jobs:
  Change_manifest_with_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Configuration for prod-test branch
        if: ${{ github.ref == 'refs/heads/test' }}
        run: |
          echo we are in main branch ${{ github.token }}
          echo ${{ github.ref }}
          ls -a
          sed -i 's/name: junction/name: junction-jay/g' *.yaml
          sed -i 's/name: junction/name: junction-jay/g' namespace.yaml
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     message: 'Deploy to production'
      #     push: false
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'test-site'
          commit_message_template: 'Deploy to production'
          # commit_message_template: '[Automated] Merged {source_ref} into target {target_branch} version:2'

      - run: echo Merge completed
